-- CREATE TABLE `usersapi`.`users` (
--   `id` int unsigned NOT NULL AUTO_INCREMENT,
--   `email` varchar(320) NOT NULL,
--   `username` varchar(26) NOT NULL,
--   `password` varchar(255) NOT NULL,
--   `favorite_movies` int unsigned,
--   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `email_UNQIUE` (`email`)
--   UNIQUE KEY `username_UNQIUE` (`username`),
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;